name: Continuous integration

# Runs on push and pull requests, any branch, Linux only (for now).

on: [push, pull_request]

jobs:
  linux-ci:
    name: Linux CI
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: bash ./.github/scripts/linux/install-deps.sh
        
      - name: Generate Makefile
        run: cmake -S . -B build/ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Wno-class-memaccess -DWITH_TESTS=ON

      - name: Build
        run: cmake --build build/ -j 2

      - name: Run tests
        run: xvfb-run ./build/giada --run-tests 